name: Build Docker And Push

on:
  push:
    branches: ['main', '*5*', '*dev*']
    tags: 
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to build'
        required: true

env:
  REGISTRY: 'ghcr.io/'
  IMAGE_NAME: blockscan

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.commit_sha || '' }}

    # Extract metadata (tags, labels) for the Docker image
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        flavor: |
          latest=auto
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=ref,event=branch
          # minimal (short sha)
          type=sha,enable=true,prefix=sha-,format=short
    - name: Echo steps.meta.outputs.bake-file
      run: cat ${{ steps.meta.outputs.bake-file }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
