name: Build Docker And Push
on:
  push:
    branches:
      - docker-compose  
      - kubernetes
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: blockscan

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/simon-tl/${{env.IMAGE_NAME}}:kubernetes
